export const siteConfig = {
  name: "Brian Kareithi",
  fullName: "Brian Kareithi",
  role: "Software Engineer, Web, Mobile & Cloud-Native Systems",
  tagline: "Software engineer shipping Next.js and React Native apps, backed by hands-on infrastructure and security experience.",
  url: "https://kareithi.vercel.app",
  title: "Brian Kareithi | Software Engineer, Web, Mobile & Cloud-Native Systems",
  description:
    "Brian Kareithi is a Software Engineer based in Nairobi, Kenya, building secure web and mobile products with Next.js, React Native and TypeScript, from architecture through deployment. IT support and infrastructure background, 6 certifications, 50+ projects delivered.",
  email: "kareithibrian2@gmail.com",
  phone: "+254119343294",
  phoneDisplay: "+254 119 343 294",
  location: "Nairobi, Kenya",
  resumePdf: "/Brian-Kareithi-Resume.pdf",
  github: "https://github.com/Brian-Kareithi",
  linkedin: "https://www.linkedin.com/in/brian-kareithi-04007637b/",
  instagram: "https://www.instagram.com/kareithi._/",
  ogImage:
    "https://ppkfgsakvcijmmhjwbcz.supabase.co/storage/v1/object/public/Photos/kareithi.jpg",
} as const;

export type PageMeta = {
  title: string;
  description: string;
  path: string;
};

/** Branded 1200×630 preview image generated by /og for a page title. */
export function ogImageFor(title: string, subtitle: string) {
  return {
    url: `/og?title=${encodeURIComponent(title)}&subtitle=${encodeURIComponent(subtitle)}`,
    width: 1200,
    height: 630,
    alt: `${title} | ${siteConfig.name}`,
  };
}

export function pageMeta({ title, description, path }: PageMeta) {
  const url = `${siteConfig.url}${path}`;
  const image = ogImageFor(title, description.length > 120 ? `${description.slice(0, 117).trimEnd()}…` : description);
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website" as const,
      url,
      siteName: siteConfig.name,
      title: `${title} | ${siteConfig.name}`,
      description,
      images: [image],
    },
    twitter: {
      card: "summary_large_image" as const,
      title: `${title} | ${siteConfig.name}`,
      description,
      images: [image.url],
    },
  };
}