// Generates /docs from the same data that powers /projects, so the site and the
// repository documentation cannot drift. Run with: npm run docs (Node 22.6+).
import { mkdirSync, writeFileSync } from "node:fs";
import { caseStudies } from "../app/lib/projects-data.ts";
import { projectDocs } from "../app/lib/project-docs.ts";

const out = new URL("../docs/", import.meta.url);
mkdirSync(new URL("projects/", out), { recursive: true });

const mermaidCard = { "1:1": "||--||", "1:N": "||--o{", "N:M": "}o--o{" };
const keyTag = { pk: "PK", fk: "FK", uq: "UK" };
const list = (items) => items.map((i) => `- ${i}`).join("\n");

function erd({ entities, relations }) {
  const lines = ["```mermaid", "erDiagram"];
  for (const r of relations) lines.push(`  ${r.from} ${mermaidCard[r.cardinality]} ${r.to} : "${r.label}"`);
  for (const e of entities) {
    lines.push(`  ${e.name} {`);
    for (const f of e.fields) lines.push(`    ${f.type.replace(/\s+/g, "_")} ${f.name}${f.key ? ` ${keyTag[f.key]}` : ""}`);
    lines.push("  }");
  }
  lines.push("```");
  return lines.join("\n");
}

function project(study) {
  const doc = projectDocs[study.id];
  const parts = [
    `# ${study.title}`,
    `> ${study.tagline}`,
    `**Status:** ${study.status} · **Access:** ${study.access.note}` +
      (study.access.demo ? ` · [Live demo](${study.access.demo})` : "") +
      (study.access.repo ? ` · [Source](${study.access.repo})` : ""),
    "## Purpose",
    doc.purpose,
    "## Problem",
    study.problem,
    "## Target audience",
    "| Audience | Needs |\n| --- | --- |\n" + doc.audience.map((a) => `| ${a.who} | ${a.needs} |`).join("\n"),
    "## Scope",
    "### In scope",
    list(doc.scope.in),
    "### Out of scope",
    list(doc.scope.out),
    "## Solution",
    study.solution.map((s, i) => `${i + 1}. ${s}`).join("\n"),
    "## Architecture",
    study.architecture.stages.join(" → ") +
      (study.architecture.branch ? `\n\nBranch from *${study.architecture.stages[study.architecture.branch.under]}*: ${study.architecture.branch.label}.` : ""),
    "## Data model",
    doc.erd ? erd(doc.erd) : doc.dataNote,
    "## Design priorities",
    list(doc.qualities),
    "## Technology",
    study.stack.join(" · "),
    "## My contribution",
    study.contribution,
  ];
  return parts.join("\n\n") + "\n";
}

for (const study of caseStudies) writeFileSync(new URL(`projects/${study.id}.md`, out), project(study));

const index = [
  "# Project documentation",
  "Product documentation for each case study on the portfolio: purpose, target audience, scope, architecture and entity-relationship diagram (ERD). Generated by `npm run docs` from `app/lib/projects-data.ts` and `app/lib/project-docs.ts`; edit those files, not these.",
  "| # | Project | Status | Data model |\n| --- | --- | --- | --- |\n" +
    caseStudies
      .map((s) => `| ${s.index} | [${s.title}](projects/${s.id}.md) | ${s.status} | ${projectDocs[s.id].erd ? `${projectDocs[s.id].erd.entities.length} entities` : "No database"} |`)
      .join("\n"),
].join("\n\n") + "\n";
writeFileSync(new URL("README.md", out), index);

console.log(`Wrote docs/README.md and ${caseStudies.length} project documents.`);
